# BROKER

broker:
  host: docker
  port: 1883
  username: null
  password: null
  client_id: Pi

# DEVICES

devices:

  # Lamp0
  - name: Lamp0
    type: digital
    pin: 16
    mode: output
    topic: relay/0

  # Lamp1
  - name: Lamp1
    type: digital
    pin: 19
    mode: output
    topic: relay/1

  # Lamp2
  - name: Lamp2
    type: digital
    pin: 20
    mode: output
    topic: relay/2

  # Lamp3
  - name: Lamp3
    type: digital
    pin: 26
    mode: output
    topic: relay/3
