#! /bin/sh
# /etc/init.d/blah
#

# Some things that run always

NAME = "Tingo"
DIR = "/home/pi/tingo"

chdir $DIR

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    sudo python tingo.py
    echo "$NAME is now running..."
    ;;
  stop)
    sudo pkill -1 -f tingo.py
    echo "$NAME has been stopped..."
    ;;
  restart)
    sudo ./tingo stop
    sudo ./tingo start
    ;;
  status)
    ps -fA | grep tingo.py
    ;;
  update)
    git pull
    sudo ./tingo restart
    ;;
  *)
    echo "Usage: sudo tingo {start|stop|restart|status|update}"
    exit 1
    ;;
esac

exit 0

